### ISSUE TITLE
an issue

### ISSUE THREAD

**Issue by yz17970** [epid8060fall2019/Ian-Bachli---Introduction#1]
Hi Ian:

Nice introduction page! I wanted to become a novelist when I was in middle school, but I never had the patience to write more than a few pages. What are the names of the main characters in your novel? What inspires you to write your novel?

Yang

**Comment by idbachli** [comment]
Hello!

Thanks for the issue! Yeah, writing can feel like running up a mountain. From what I have learned, it's a lot of small steps that add together to make the book. You have to take it chapter by chapter; page by page. I'll upload some changes as soon as I can. Thanks!

**Comment by idbachli** [comment]
I uploaded a tag of inspiration to write in my introduction page.
